version: "3"
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MAX_CPU_CORES: 2
      MAX_RAM: 1g
      COMPUTER_TYPE: worker
    volumes:
     - /tmp/results_worker:/results
    #cpuset: "0,1"
    #mem_limit: 1g


  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MAX_CPU_CORES: 2
      MAX_RAM: 1g
      COMPUTER_TYPE: server
    #cpuset: "2,3"
    #mem_limit: 1g
    volumes:
     - /tmp/results_server:/results

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:alpine
